<?php
$_helper = $this->helper('Solwin\Cpanel\Helper\CssSetting');
$header_type = $_helper->getCpanelDesignConfig('cpanelsection/headergroup/headertype');
?>
<?php if ($header_type == 1) { ?>
    <header class="page-header htype-<?php echo $header_type; ?>">
        <div class="panel wrapper">
            <div class="panel header">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("top.links"); ?>
            </div>
        </div>
        <div class="header content">
            <?php echo $this->getChildHtml("logo"); ?>
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </header>
<?php } else if ($header_type == 2) { ?>
    <header class="page-header htype-<?php echo $header_type; ?>">
        <div class="panel wrapper">
            <div class="panel header">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("top.links"); ?>
            </div>
        </div>
        <div class="header content">
            <div class="h-inner">
                <?php echo $this->getChildHtml("logo"); ?>
                <?php echo $this->getChildHtml("navigation.sections"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
                <?php echo $this->getChildHtml("top.search"); ?>
            </div>
        </div>
    </header>
<?php } else if ($header_type == 3) { ?>
    <header class="page-header htype-<?php echo $header_type; ?>">
        <div class="panel wrapper">
            <div class="panel header">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("top.links"); ?>
            </div>
        </div>
        <div class="header content">
            <?php echo $this->getChildHtml("logo"); ?>
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </header>
<?php } else if ($header_type == 6) { ?>
    <header class="page-header htype-<?php echo $header_type; ?>">
        <div class="panel wrapper">
            <div class="panel header">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("top.links"); ?>
            </div>
        </div>
        <div class="header content">
            <div class="h-inner">
                <?php echo $this->getChildHtml("logo"); ?>
                <?php echo $this->getChildHtml("navigation.sections"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
                <?php echo $this->getChildHtml("top.search"); ?>
            </div>
        </div>
    </header>
<?php } else if ($header_type == 7) { ?>
    <header class="page-header htype-<?php echo $header_type; ?>">
        <div class="panel wrapper">
            <div class="panel header">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("top.links"); ?>
            </div>
        </div>
        <div class="header content">
            <div class="h-inner">
                <?php echo $this->getChildHtml("logo"); ?>
                <?php echo $this->getChildHtml("navigation.sections"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
                <?php echo $this->getChildHtml("top.search"); ?>
            </div>
        </div>
    </header>
<?php } ?>