<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-list';

    $mode = 'list';

    $image = 'new_products_content_widget_list';
    $hover_img = 'category_page_list_hover';
    $title = __('<span>Latest</span> Products');
    $items = $block->getProductCollection()->getItems();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = true;
}
?>

<?php if ($exist): ?>
    <?php
    $cpanel_helper = $this->helper('Solwin\Cpanel\Helper\Data');
    $isNewLabel = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/newlabel');
    $isSaleLabel = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/salelabel');
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
    $Enable_aspect_ratio = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/image_aspect_ratio');
    $img_width = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/image_ratio_width');
    $img_height = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/image_ratio_height');
    $show_rating_star = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_rating_star');
    $show_product_price = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_product_price');
    $show_actions = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_actions');
    $show_addtocompare = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_addtocompare');
    $show_addtowishlist = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_addtowishlist');
    $show_productview = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_productview');
    $show_alternative_image = $cpanel_helper->getCpanelConfigValue('cpanelsection/listpagegroup/show_alternative_image');
    $mediaurl = $cpanel_helper->getMediaUrl() . 'themecss/box/';
    ?>
    <div class="block widget pad-main-top cus-box block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-title-main">
            <h2 role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></h2>
            <div class="title-img">
                <span></span>
            </div>
        </div>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="products list items product-items three_blocks <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <div class="product photo product-item-photo">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                    <?php
                                    if ($Enable_aspect_ratio) {
                                        $productImage = $_imagehelper->init($_item, $image)
                                                ->constrainOnly(FALSE)
                                                ->keepAspectRatio(TRUE)
                                                ->keepFrame(FALSE)
                                                ->resize($img_width);
                                    } else {
                                        $productImage = $_imagehelper->init($_item, $image)
                                                ->resize($img_width, $img_height);
                                    }
                                    $productImageUrl = $productImage->getUrl();
                                    ?>
                                    <img class="product-image-photo pd-img" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                    <?php if ($show_alternative_image) { ?>
                                        <?php
                                        if ($Enable_aspect_ratio) {
                                            $productHoverImage = $_imagehelper->init($_item, $hover_img)
                                                    ->constrainOnly(FALSE)
                                                    ->keepAspectRatio(TRUE)
                                                    ->keepFrame(FALSE)
                                                    ->resize($img_width);
                                        } else {
                                            $productHoverImage = $_imagehelper->init($_item, $hover_img)
                                                    ->resize($img_width, $img_height);
                                        }
                                        $productHoverImageUrl = $productHoverImage->getUrl();
                                        ?>
                                        <img  class="product-image-photo ph_img" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                    <?php } ?>
                                </a>
                            </div>
                            <?php
                            /**
                             * Check if "new" label is enabled and if product has from new date & to new date
                             */
                            if ($isNewLabel) {
                                $fromDate = $_item->getNewsFromDate();
                                $toDate = $_item->getNewsToDate();
                                if (isset($fromDate) && isset($toDate)) {
                                    $fromDate = strtotime($fromDate);
                                    $toDate = strtotime($toDate);
                                    $now = strtotime(date("Y-m-d h:m:s"));

                                    if ($fromDate <= $now && $now <= $toDate) {
                                        ?>
                                        <span class="new-lbl">New</span>
                                        <?php
                                    }
                                }
                            }
                            ?>

                            <?php
                            /**
                             * Check if "sale" label is enabled and if product has special price with from & to special price
                             */
                            if ($isSaleLabel) {
                                $special_price = number_format($_item->getSpecialPrice(), 2);
                                $regular_price = number_format($_item->getPrice(), 2);
                                if (isset($special_price) && $special_price > 0) {
                                    if ($special_price < $regular_price) {
                                        $fromSpecialDate = $_item->getSpecialFromDate();
                                        $toSpecialDate = $_item->getSpecialToDate();

                                        if (isset($fromSpecialDate) && isset($toSpecialDate)) {
                                            $fromSpecialDate = strtotime($fromSpecialDate);
                                            $toSpecialDate = strtotime($toSpecialDate);
                                            $now = strtotime(date("Y-m-d h:m:s"));

                                            if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                ?>
                                                <span class="sale-lbl">Sale</span>
                                                <?php
                                            }
                                        }
                                    }
                                }
                            }
                            ?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                           <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?php if ($show_rating_star) { ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType, TRUE) ?>
                                    <?php } ?>
                                <?php endif; ?>
                                <?php if ($show_product_price) { ?>
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                <?php } ?>
                                <?php if ($show_actions) { ?>
                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <?php if ($show_addtowishlist) { ?>    
                                                            <a href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php } ?>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                        <?php if ($show_addtocompare) { ?>    
                                                            <a href="#" class="action tocompare"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>"
                                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'>
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php } ?>
                                                    <?php endif; ?>
                                                    <?php if ($show_productview) { ?>
                                                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                                           class="action cus-addto toview"
                                                           title="<?php echo $block->escapeHtml(__('View')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('View')); ?>"
                                                           role="button">
                                                            <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                                                            <div class="span-hov"></div>
                                                        </a>
                                                    <?php } ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                <?php } ?>
                                <?php if ($description): ?>
                                    <div class="product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
