<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$cpanel_helper = $this->helper('Solwin\Cpanel\Helper\CssSetting');
$header_type = $cpanel_helper->getCpanelDesignConfig('cpanelsection/headergroup/headertype');
?>
<?php if ($header_type == 1 ) { ?>
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                               "formSelector":"#search_mini_form",
                               "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                               "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
<?php } else if ($header_type == 2) { ?>
    <div id="top_search" class="block block-search">
        <div class="s-icon">
            <i class="fa fa-search"></i>
        </div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                               "formSelector":"#search_mini_form",
                               "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                               "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <script>
        require(['jquery'], function () {
            jQuery('.s-icon').hover(function () {
                jQuery('#top_search').find('.block-content').addClass('bactive');
                jQuery('#top_search').hover(function () {
                    jQuery(this).find('.block-content').addClass('bactive');
                }, function () {
                    jQuery(this).find('.block-content').removeClass('bactive');
                });
            });
        });
    </script>
<?php } else if ($header_type == 3) { ?>
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                               "formSelector":"#search_mini_form",
                               "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                               "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
<?php } else if ($header_type == 6) { ?>
    <div id="top_search" class="block block-search">
        <div class="s-icon">
            <i class="fa fa-search"></i>
        </div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                               "formSelector":"#search_mini_form",
                               "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                               "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <script>
        require(['jquery'], function () {
            jQuery('.s-icon').hover(function () {
                jQuery('#top_search').find('.block-content').addClass('bactive');
                jQuery('#top_search').hover(function () {
                    jQuery(this).find('.block-content').addClass('bactive');
                }, function () {
                    jQuery(this).find('.block-content').removeClass('bactive');
                });
            });
        });
    </script>
<?php } else if ($header_type == 7) { ?>
    <div id="top_search" class="block block-search">
        <div class="s-icon">
            <i class="fa fa-search"></i>
        </div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                               "formSelector":"#search_mini_form",
                               "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                               "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <script>
        require(['jquery'], function () {
            jQuery('.s-icon').hover(function () {
                jQuery('#top_search').find('.block-content').addClass('bactive');
                jQuery('#top_search').hover(function () {
                    jQuery(this).find('.block-content').addClass('bactive');
                }, function () {
                    jQuery(this).find('.block-content').removeClass('bactive');
                });
            });
        });
    </script>
<?php } ?>

