<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
<div class="logo-outer">
    <?php if ($block->isHomePage()): ?>
        <strong class="logo">
        <?php else: ?>
            <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <?php endif ?>
            <div class="logo-inner">
                <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                     alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
                     <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                     <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
                     />
            </div>
            <?php if ($block->isHomePage()): ?>
        </strong>
    <?php else: ?>
    </a>
<?php endif ?>
</div>